server:
  port: 8083
spring:
  application:
    name: Home
  datasource:
    url: jdbc:mysql://localhost:3306/spr240
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update