
server:
  port: 8081
spring:
  application:
    name: Home
  datasource:
    url: jdbc:postgresql://dpg-d360b97diees738n4bp0-a.oregon-postgres.render.com:5432/user_ybik
    username: user_ybik_user
    password: Kr9Yr1UigcmrVBJXo05FonFyMKbgrgFL
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
